name: Searing Vengeance
automation:
  - type: target
    target: self
    effects:
      - type: damage
        damage: -{{caster.max_hp//2}} [healing]
        overheal: false
  - type: target
    target: all
    effects:
      - type: damage
        damage: 2d8+{intelligenceMod} [radiant]
        overheal: false
      - type: ieffect2
        name: Blinded
        duration: "1"
        effects:
          attack_advantage: "-1"
        attacks: []
        buttons: []
        end: true
        conc: false
        desc: It is blinded until the end of the current turn.
        stacking: false
        save_as: null
        parent: null
        target_self: false
        tick_on_caster: true
  - type: text
    text: >-
      When you have to make a death saving throw at the start of your turn, you
      can instead spring back to your feet with a burst of radiant energy. You
      regain hit points equal to half your hit point maximum, and then you stand
      up if you so choose. Each creature of your choice that is within 30 feet
      of you takes radiant damage equal to 2d8 + your Intelligence modifier, and
      it is blinded until the end of the current turn.


      Once you use this feature, you can't use it again until you finish a long rest.
    title: Effect
_v: 2
verb: reacts with
activation_type: 8
