name: Hexblade's Curse
automation:
  - type: variable
    name: warlock
    value: caster.levels.get('Warlock')
    onError: "0"
  - type: target
    target: self
    effects:
      - type: ieffect2
        name: Hexblade's Curse
        duration: "10"
        desc: >-
          You gain a bonus of {{proficiencyBonus}} to damage rolls against the
          target
           - Your attacks crit on a 19 or 20 against them
           - If they die, heal for {{warlock+intelligenceMod}}
        buttons:
          - label: Hexblade's Curse (Heal)
            automation:
              - type: target
                target: self
                effects:
                  - type: variable
                    name: warlock
                    value: caster.levels.get('Warlock')
                    onError: "0"
                  - type: damage
                    damage: -({max((warlock+intelligenceMod), 1)}) [healing]
                  - type: remove_ieffect
            verb: absorbs the Essence of their Foe
            style: "3"
        parent: ""
        save_as: curse
  - type: target
    target: all
    effects:
      - type: ieffect2
        name: Hexblade's Cursed
        duration: "10"
        tick_on_caster: false
        parent: curse
        desc: >-
          Cursed by {{caster.name}}
           - They gain a bonus of {{proficiencyBonus}} to damage rolls against the target
           - Their attacks crit on a 19 or 20 against them
           - If they die, heal for {{warlock+intelligenceMod}}
  - type: text
    text: >-
      As a bonus action, choose one creature you can see within 30 feet of you.
      The target is cursed for 1 minute. The curse ends early if the target
      dies, you die, or you are incapacitated. Until the curse ends, you gain
      the following benefits:


      - You gain a bonus to damage rolls against the cursed target. The bonus equals your proficiency bonus.

      - Any attack roll you make against the cursed target is a critical hit on a roll of 19 or 20 on the d20.

      - If the cursed target dies, you regain hit points equal to your warlock level + your Intelligence modifier (minimum of 1 hit point).
    title: Effect
  - type: counter
    counter: Hexblade's Curse
    amount: "1"
    errorBehaviour: raise
_v: 2
proper: true
verb: enacts their
activation_type: 3
