embed <drac2>
cc="The Pioneers of the Veil"
CC="The Craftsmen's Fellowship"
dd="The Sanctified Order of Iados"
DD="The Luminal Order"
ee="The Nexus Lorekeepers"
desc1="**Type of Guild**: Explorers from real life Earth. Modern stuff. **Guild Description**: They identify themselves as 'The Pioneers of the Veil,' symbolising their role as the first individuals from Earth to find themselves in this enchanting realm through the mysterious portal. The name carries a sense of adventure and the unknown, reflecting their determination to pioneer a new life in Mystara while preserving their Earthly origins.Within the confines of The Glass Haven, these survivors have ingeniously combined remnants of modern conveniences with the rustic aesthetics of Nexus, forging a unique and harmonious existence at the crossroads of two worlds. **Guild Leader**: Sarah Thornbridge is known as the guild's practical leader, offering guidance and solutions to the daily challenges they face. She is particularly skilled at crafting makeshift tools and finding edible plants in the wild. Her mission is to ensure the group's survival while seeking a way back to Earth."
desc2= "**Type of Guild**: Artisans Guild **Guild Description**: Once renowned for their exquisite craftsmanship, The Craftsmen's Fellowship has fallen on hard times in recent years due to the overall decline of Nexus. This guild was known for producing unique and masterful works of art and functional items, but now many of its members have lost their inspiration. The guild hall is a grand but dusty building filled with the echoes of past glory. **Guild Leader**: Vorin Stoneheart is a formidable dwarf with a powerful build, impressive beard, and a perpetually soot-stained apron. His hands, however, bear the scars of countless hours at the forge. Role: Vorin is the guild's master blacksmith and one of the last remaining craftsmen of exceptional skill. However, he has lost his inspiration and struggles to create new masterpieces"
desc3="**Type of Guild**: Religious Guild. **Guild Description**: The Sanctified Order of Iados, often simply referred to as the Iadoian Order, is a religious guild devoted to the worship of Iados, the God of Light and Renewal. Within the walled city of Nexus, their grand temple, the Luminous Sanctuary, once shone as a beacon of hope and faith. However, like many aspects of Nexus, the Iadoian Order has fallen on hard times. The decline in faith and followers has cast a shadow over the once-proud guild. Their current headquarters, the Luminous Sanctuary, is in disrepair, with fading murals and crumbling spires. **Guild Leader**: High Priestess Lorianne Sunshroud is a serene and wise elf with golden robes that seem to radiate an aura of divine grace. Her long silver hair flows like a gentle waterfall, and her voice is soothing. Lorianne is the guild's spiritual leader, dedicated to the revitalisation of faith in Iados. She is deeply troubled by the decline of their once-flourishing temple."
desc4="**Type of Guild**: Arcane Guild **Guild Description**: The Luminal Order is the once-prestigious Arcane Guild of The Nexus, dedicated to the study, practice, and preservation of arcane magic. In its heyday, it was renowned for its contributions to the understanding of the mystical arts. However, in recent times, the guild has fallen into decline due to dwindling membership and a lack of magical discoveries. **Guild Leader**: Magistra Selene Starweaver, an elderly elf with silver hair and deep blue robes adorned with celestial patterns. She specializes in divination magic."
desc5="**Type of Guild**: Scholastic Guild **Guild Description**: The Nexus Lorekeepers is a modest guild dedicated to the pursuit of knowledge and the preservation of historical records. However, the decline in Nexus has taken its toll on the guild's resources and influence, leaving it in a state of disarray. The guild's library, once renowned, is now in disrepair, and many valuable tomes have gone missing or deteriorated. **Guild Leader**: Professor Thalina Astronomus is a scholarly gnome with oversized glasses, known for her expertise in astronomy and cosmology. She often paces around the guild's library, deep in thought. Thalina is the head of The Nexus Lorekeepers and is deeply concerned about the decline of both the guild and Nexus itself. She is determined to preserve knowledge and encourage exploration beyond Nexus."
character().create_cc_nx(cc, desc=desc1, initial_value=10)
character().create_cc_nx(CC, desc=desc2, initial_value=10)
character().create_cc_nx(dd, desc=desc3, initial_value=10)
character().create_cc_nx(DD, desc=desc4, initial_value=10)
character().create_cc_nx(ee, desc=desc5, initial_value=10)
text=f''' -title "{name} is a Born Nexian" -f "{cc}|{character().cc_str(cc)}" -f "{CC}|{character().cc_str(CC)}" -f "{dd}|{character().cc_str(dd)}" -f "{DD}|{character().cc_str(DD)}" -f "{ee}|{character().cc_str(ee)}" -f "Additional Benefits|- You gain a permanent modest lifestyle home which means that you pay half the the price of modest lifestyle. You pay normally for any other lifestyle though.
- You gain access to a dedicated channel that offers information about the starting region.
- Interactions with the local tribes in the wilds is easier for you. You may communicate basic meanings without needing to use a specific language. It takes double the time to do this than normal speech. This doesnt mean that they will consider you a friend though. But they will be more trusting if you are the one who speaks for the group when you interact with them." '''
return text
</drac2> -thumb {{image}}
